config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :followings
    end
  end

  resources :items, only: [:show, :new, :edit, :update, :destroy]
  resources :ownerships, only: [:create, :destroy]
  
  resources :mypages, only: [:index, :new, :create]

  get 'registitem', to: 'mypages#new'
  post 'registitem', to: 'mypages#create'
  
  resources :myitems, only: [:index]

  resources :microposts, only: [:create, :destroy]
  resources :communities, only: [:index, :show, :new, :create]
  resources :relationships, only: [:create, :destroy]
end

app/models/ownership.rb
class Ownership < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/ownerships_controller.rb
class OwnershipsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])

    # Want 関係として保存
    if params[:type] == 'Want'
      current_user.want(@item)
      flash[:success] = '商品を Want しました。'
    end

    redirect_back(fallback_location: root_path)
  end

  def destroy
    @item = Item.find(params[:item_id])

    if params[:type] == 'Want'
      current_user.unwant(@item) 
      flash[:success] = '商品の Want を解除しました。'
    end

    redirect_back(fallback_location: root_path)
  end
end

app/views/ownerships/_want_button.html.erb
<% if current_user.want?(item) %>
  <%= form_tag(ownership_path(item.id), method: :delete) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want', class: 'btn btn-success' %>
  <% end %>
<% else %>
  <%= form_tag(ownerships_path) do %>
    <%= hidden_field_tag :item_id, item.id %>
    <%= hidden_field_tag :type, 'Want' %>
    <%= submit_tag 'Want it', class: 'btn btn-primary' %>
  <% end %>
<% end %>