config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :followings
    end
  end

  resources :items, only: [:show, :new, :edit, :update, :destroy]
  resources :ownerships, only: [:create, :destroy]
  
  resources :mypages, only: [:index, :new, :create]

  get 'registitem', to: 'mypages#new'
  post 'registitem', to: 'mypages#create'
  
  resources :myitems, only: [:index]

  resources :microposts, only: [:create, :destroy]
  resources :communities, only: [:index, :show, :new, :create]
  resources :relationships, only: [:create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :detail, presence: true, length: { maximum: 255 }
  
  has_many :ownerships, dependent: :destroy
  has_many :users, through: :ownerships
  
  has_many :wants
  has_many :want_users, through: :wants, class_name: 'User', source: :user
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :destroy]

  def new
    @items = []

    keyword = "%#{params[:keyword]}%"
    if keyword
      @items = Item.where("name like ? or detail like ?", keyword, keyword).order('updated_at DESC')
    end
  end
  
  def show
    @item = Item.find(params[:id])
    @want_users = @item.want_users
    @user = User.find(@item.user_id)
  end
  
  def edit
    @item = Item.find_by(id: params[:id], user_id: current_user.id)
  end

  def update
    @item = Item.find_by(id: params[:id], user_id: current_user.id)

    if @item.update(item_params)
      flash[:success] = '商品 は正常に更新されました'
      redirect_to @item
    else
      flash.now[:danger] = '商品 は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @item.destroy
    flash[:success] = '商品を削除しました。'
    redirect_to myitems_path
  end

  private

  def correct_user
    @item = Item.find_by(id: params[:id], user_id: current_user.id)
    unless @item
      redirect_to item_path(params[:id])
    end
  end

  def item_params
    params.require(:item).permit(:name, :detail)
  end
end

app/views/items/_items.html.erb
<% if items.present? %>
  <div class="row">
    <% items.each do |item| %>
      <div class="item">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <p class="item-title"><%= link_to item.name, item %></p>
            </div>
            <div class="panel-body text-center">
              <% if logged_in? %>
                <% unless current_user == item.user %>
                  <p class="user-name"><%= link_to item.user.name, user_path(item.user) %></p>
                  <div class="buttons text-center">
                      <%= render 'ownerships/want_button', item: item %>
                  </div>
                <% else %>
                  <p class="user-name"><%= link_to item.user.name, mypages_path %></p>
                <% end %>
              <% else %>
                <p class="user-name"><%= link_to item.user.name, user_path(item.user) %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/_myitems.html.erb
<% if items.present? %>
  <div class="row">
    <% items.each do |item| %>
      <div class="myitem">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <p class="myitem-title"><%= link_to item.name, item %></p>
            </div>
            <div class="panel-body text-center">
              <p class="myitem-detail"><%= truncate(item.detail, length: 10) %></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">Item Edit</div>
      <div class="panel-body">
        <%= form_for(@item) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'Item Name' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :detail, 'Item Detail' %>
            <%= f.text_field :detail, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit 'Edit', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(new_item_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "Enter any search keywords", size: 40 %>
        </div>
        <%= submit_tag 'Search Items', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<%= render 'items', items: @items %>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-3 col-sm-6 col-xs-12 col-md-offset-3">
    <div class="item">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <p class="item-title"><%= @item.name %></p>
        </div>
        <div class="panel-body">
          <p class="item-detail"><%= @item.detail %></p>
          <div class="buttons text-center">
            <% if logged_in? %>
              <% unless current_user == @user %>
                <%= render 'ownerships/want_button', item: @item %>
              <% else %>
                <%= link_to "Edit", edit_item_path(@item), class: 'btn btn-default btn-xs' %>
                <%= link_to "Delete", @item, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-xs' %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="want-users">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          Wantしたユーザ
        </div>
        <div class="panel-body">
          <% @want_users.each do |user| %>
            <%= link_to user.name, user_path(user) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>