config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create] do
    member do
      get :followings
    end
  end

  resources :items, only: [:show, :new, :edit, :update, :destroy]
  resources :ownerships, only: [:create, :destroy]
  
  resources :mypages, only: [:index, :new, :create]

  get 'registitem', to: 'mypages#new'
  post 'registitem', to: 'mypages#create'
  
  resources :myitems, only: [:index]

  resources :microposts, only: [:create, :destroy]
  resources :communities, only: [:index, :show, :new, :create]
  resources :relationships, only: [:create, :destroy]
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :microposts
  has_many :users, through: :microposts
  
  validates :name, presence: true, length: { maximum: 255 }
  validates :detail, presence: true, length: { maximum: 255 }
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :require_user_logged_in, only: [:show]

  def index
    @communities = Community.all
  end

  def show
    @community = Community.find(params[:id])
    @micropost = current_user.microposts.build
    @microposts = @community.microposts.order('created_at DESC')
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)

    if @community.save
      flash[:success] = 'コミュニティを登録しました。'
      redirect_to communities_path
    else
      flash.now[:danger] = 'コミュニティの登録に失敗しました。'
      render :new
    end
  end

  private

  def community_params
    params.require(:community).permit(:name, :detail)
  end
end

app/views/communities/_communities.html.erb
<% if communities.present? %>
  <div class="row">
    <% communities.each do |community| %>
      <div class="community-list">
        <p class="name"><%= link_to community.name, community_path(community.id) %></p>
        <p class="detail"><%= community.detail %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/communities/create.html.erb
<h1>Communities#create</h1>
<p>Find me in app/views/communities/create.html.erb</p>

app/views/communities/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="community">
      <div class="community-inner">
        <div class="community-contents">
          <h1>Community</h1>
        </div>
      </div>
    </div>
    
    <div class="community-new text-center">
      <%= link_to new_community_path do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
          New Community Regist
      <% end %>
    </div>

    <%= render 'communities/communities', communities: @communities %>
    
  </div>
</div>

app/views/communities/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">Community Register</div>
      <div class="panel-body">
        <%= form_for(@community) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'Community Name' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :detail, 'Detail' %>
            <%= f.text_field :detail, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit 'Regist', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/communities/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="community">
      <div class="community-inner">
        <div class="community-contents">
          <h1><%= @community.name %></h1>
        </div>
      </div>
    </div>
    <div class="community-detail">
      <%= @community.detail %>
    </div>

  </div>

    <aside class="col-md-4">
      <%= form_for(@micropost) do |f| %>
        <div class="form-group">
          <%= f.text_area :content, class: 'form-control', rows: 5 %>
        </div>
        <%= hidden_field_tag :community_id, @community.id %>
        <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
      <% end %>
    </aside>
    <div class="col-xs-8">
      <%= render 'microposts/microposts', microposts: @microposts %>
    </div>
</div>